package com.nfcmeeting.nfcmeeting.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nfcmeeting.nfcmeeting.dao.AuthUser;
import com.nfcmeeting.nfcmeeting.dao.Meeting;

import com.nfcmeeting.nfcmeeting.dao.AuthUserDao;
import com.nfcmeeting.nfcmeeting.dao.MeetingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig authUserDaoConfig;
    private final DaoConfig meetingDaoConfig;

    private final AuthUserDao authUserDao;
    private final MeetingDao meetingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        authUserDaoConfig = daoConfigMap.get(AuthUserDao.class).clone();
        authUserDaoConfig.initIdentityScope(type);

        meetingDaoConfig = daoConfigMap.get(MeetingDao.class).clone();
        meetingDaoConfig.initIdentityScope(type);

        authUserDao = new AuthUserDao(authUserDaoConfig, this);
        meetingDao = new MeetingDao(meetingDaoConfig, this);

        registerDao(AuthUser.class, authUserDao);
        registerDao(Meeting.class, meetingDao);
    }
    
    public void clear() {
        authUserDaoConfig.clearIdentityScope();
        meetingDaoConfig.clearIdentityScope();
    }

    public AuthUserDao getAuthUserDao() {
        return authUserDao;
    }

    public MeetingDao getMeetingDao() {
        return meetingDao;
    }

}
