package com.nfcmeeting.nfcmeeting.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MEETING".
 */
@Entity
public class Meeting {

    @Id
    private short meetingId;

    @NotNull
    private String title;

    @NotNull
    private String content;

    @NotNull
    private String beginTime;

    @NotNull
    private String endTime;

    @Generated
    public Meeting() {
    }

    public Meeting(short meetingId) {
        this.meetingId = meetingId;
    }

    @Generated
    public Meeting(short meetingId, String title, String content, String beginTime, String endTime) {
        this.meetingId = meetingId;
        this.title = title;
        this.content = content;
        this.beginTime = beginTime;
        this.endTime = endTime;
    }

    public short getMeetingId() {
        return meetingId;
    }

    public void setMeetingId(short meetingId) {
        this.meetingId = meetingId;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    @NotNull
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(@NotNull String content) {
        this.content = content;
    }

    @NotNull
    public String getBeginTime() {
        return beginTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBeginTime(@NotNull String beginTime) {
        this.beginTime = beginTime;
    }

    @NotNull
    public String getEndTime() {
        return endTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime(@NotNull String endTime) {
        this.endTime = endTime;
    }

}
